# Default Bearer token (hardcoded in Lingvanex JS, can be overridden)
DEFAULT_BEARER_TOKEN = 'Bearer a_25rccaCYcBC9ARqMODx2BV2M0wNZgDCEl3jryYSgYZtF1a702PVi4sxqi2AmZWyCcw4x209VXnCYwesx'

DEFAULT_RAISE_EXCEPTION = False

# API endpoints
API_BASE_URL = 'https://api-b2b.backenster.com/b1/api/v3'
TRANSLATE_URL = API_BASE_URL + '/translate/'
GET_LANGUAGES_URL = API_BASE_URL + '/getLanguages'

# Maps full_code (e.g. 'en_US') -> english name in lowercase
LANGUAGES = {
    'af_ZA': 'afrikaans',
    'sq_AL': 'albanian',
    'am_ET': 'amharic',
    'ar_EG': 'arabic',
    'ar_SA': 'arabic (saudi arabia)',
    'ar_AE': 'arabic (united arab emirates)',
    'hy_AM': 'armenian',
    'az_AZ': 'azerbaijani',
    'eu_ES': 'basque',
    'be_BY': 'belarusian',
    'bn_BD': 'bengali',
    'bs_BA': 'bosnian',
    'bg_BG': 'bulgarian',
    'ca_ES': 'catalan',
    'ceb_PH': 'cebuano',
    'ny_MW': 'chichewa',
    'zh-Hans_CN': 'chinese (simplified)',
    'zh-Hant_TW': 'chinese (traditional)',
    'co_FR': 'corsican',
    'hr_HR': 'croatian',
    'cs_CZ': 'czech',
    'da_DK': 'danish',
    'nl_NL': 'dutch',
    'en_GB': 'english',
    'en_AU': 'english (australian)',
    'en_US': 'english (usa)',
    'eo_WORLD': 'esperanto',
    'et_EE': 'estonian',
    'fi_FI': 'finnish',
    'fr_FR': 'french',
    # 'fr_CA': 'french (canada)',
    'fy_NL': 'frisian',
    'gl_ES': 'galician',
    'ka_GE': 'georgian',
    'de_DE': 'german',
    'el_GR': 'greek',
    'gu_IN': 'gujarati',
    'ht_HT': 'haitian creole',
    'ha_NE': 'hausa',
    'haw_US': 'hawaiian',
    'he_IL': 'hebrew',
    'hi_IN': 'hindi',
    'hmn_CN': 'hmong',
    'hu_HU': 'hungarian',
    'is_IS': 'icelandic',
    'ig_NG': 'igbo',
    'id_ID': 'indonesian',
    'ga_IE': 'irish',
    'it_IT': 'italian',
    'ja_JP': 'japanese',
    'jv_ID': 'javanese',
    'kn_IN': 'kannada',
    'kk_KZ': 'kazakh',
    'km_KH': 'khmer',
    'rw_RW': 'kinyarwanda',
    'ko_KR': 'korean',
    'ku_IR': 'kurdish',
    'ky_KG': 'kyrgyz',
    'lo_LA': 'lao',
    'la_VAT': 'latin',
    'lv_LV': 'latvian',
    'lt_LT': 'lithuanian',
    'lb_LU': 'luxembourgish',
    'mk_MK': 'macedonian',
    'mg_MG': 'malagasy',
    'ms_MY': 'malay',
    'ml_IN': 'malayalam',
    'mt_MT': 'maltese',
    'mi_NZ': 'maori',
    'mr_IN': 'marathi',
    'mn_MN': 'mongolian',
    'my_MM': 'myanmar (burmese)',
    'ne_NP': 'nepali',
    'no_NO': 'norwegian',
    'or_OR': 'odia',
    'ps_AF': 'pashto',
    'fa_IR': 'persian',
    'pl_PL': 'polish',
    'pt_BR': 'portuguese (brazil)',
    'pt_PT': 'portuguese (portugal)',
    'pa_PK': 'punjabi',
    'ro_RO': 'romanian',
    'ru_RU': 'russian',
    'sm_WS': 'samoan',
    'gd_GB': 'scottish gaelic',
    'sr-Cyrl_RS': 'serbian',
    'st_LS': 'sesotho',
    'sn_ZW': 'shona',
    'sd_PK': 'sindhi',
    'si_LK': 'sinhala',
    'sk_SK': 'slovak',
    'sl_SI': 'slovenian',
    'so_SO': 'somali',
    'es_ES': 'spanish',
    'es_MX': 'spanish (mexico)',
    'es_US': 'spanish (united states)',
    'su_ID': 'sundanese',
    'sw_TZ': 'swahili',
    'sv_SE': 'swedish',
    'tl_PH': 'tagalog',
    'tg_TJ': 'tajik',
    'ta_IN': 'tamil',
    'tt_TT': 'tatar',
    'te_IN': 'telugu',
    'th_TH': 'thai',
    'tr_TR': 'turkish',
    'tk_TM': 'turkmen',
    'uk_UA': 'ukrainian',
    'ur_PK': 'urdu',
    'ug_CN': 'uyghur',
    'uz_UZ': 'uzbek',
    'vi_VN': 'vietnamese',
    'cy_GB': 'welsh',
    'xh_ZA': 'xhosa',
    'yi_IL': 'yiddish',
    'yo_NG': 'yoruba',
    'zu_ZA': 'zulu',
}

# Maps english name in lowercase -> full_code
LANGCODES = {v: k for k, v in LANGUAGES.items()}

# Maps full_code -> native/display name (codeName from lang.json)
LANGNAMES = {
    'af_ZA': 'Afrikaans',
    'sq_AL': 'Albanian',
    'am_ET': 'Amharic',
    'ar_EG': 'Arabic',
    'ar_SA': 'Arabic (Saudi Arabia)',
    'ar_AE': 'Arabic (United Arab Emirates)',
    'hy_AM': 'Armenian',
    'az_AZ': 'Azerbaijani',
    'eu_ES': 'Basque',
    'be_BY': 'Belarusian',
    'bn_BD': 'Bengali',
    'bs_BA': 'Bosnian',
    'bg_BG': 'Bulgarian',
    'ca_ES': 'Catalan',
    'ceb_PH': 'Cebuano',
    'ny_MW': 'Chichewa',
    'zh-Hans_CN': 'Chinese (Simplified)',
    'zh-Hant_TW': 'Chinese (Traditional)',
    'co_FR': 'Corsican',
    'hr_HR': 'Croatian',
    'cs_CZ': 'Czech',
    'da_DK': 'Danish',
    'nl_NL': 'Dutch',
    'en_GB': 'English',
    'en_AU': 'English (Australian)',
    'en_US': 'English (USA)',
    'eo_WORLD': 'Esperanto',
    'et_EE': 'Estonian',
    'fi_FI': 'Finnish',
    'fr_FR': 'French',
    'fr_CA': 'French (Canada)',
    'fy_NL': 'Frisian',
    'gl_ES': 'Galician',
    'ka_GE': 'Georgian',
    'de_DE': 'German',
    'el_GR': 'Greek',
    'gu_IN': 'Gujarati',
    'ht_HT': 'Haitian Creole',
    'ha_NE': 'Hausa',
    'haw_US': 'Hawaiian',
    'he_IL': 'Hebrew',
    'hi_IN': 'Hindi',
    'hmn_CN': 'Hmong',
    'hu_HU': 'Hungarian',
    'is_IS': 'Icelandic',
    'ig_NG': 'Igbo',
    'id_ID': 'Indonesian',
    'ga_IE': 'Irish',
    'it_IT': 'Italian',
    'ja_JP': 'Japanese',
    'jv_ID': 'Javanese',
    'kn_IN': 'Kannada',
    'kk_KZ': 'Kazakh',
    'km_KH': 'Khmer',
    'rw_RW': 'Kinyarwanda',
    'ko_KR': 'Korean',
    'ku_IR': 'Kurdish',
    'ky_KG': 'Kyrgyz',
    'lo_LA': 'Lao',
    'la_VAT': 'Latin',
    'lv_LV': 'Latvian',
    'lt_LT': 'Lithuanian',
    'lb_LU': 'Luxembourgish',
    'mk_MK': 'Macedonian',
    'mg_MG': 'Malagasy',
    'ms_MY': 'Malay',
    'ml_IN': 'Malayalam',
    'mt_MT': 'Maltese',
    'mi_NZ': 'Maori',
    'mr_IN': 'Marathi',
    'mn_MN': 'Mongolian',
    'my_MM': 'Myanmar (Burmese)',
    'ne_NP': 'Nepali',
    'no_NO': 'Norwegian',
    'or_OR': 'Odia',
    'ps_AF': 'Pashto',
    'fa_IR': 'Persian',
    'pl_PL': 'Polish',
    'pt_BR': 'Portuguese (Brazil)',
    'pt_PT': 'Portuguese (Portugal)',
    'pa_PK': 'Punjabi',
    'ro_RO': 'Romanian',
    'ru_RU': 'Russian',
    'sm_WS': 'Samoan',
    'gd_GB': 'Scottish Gaelic',
    'sr-Cyrl_RS': 'Serbian',
    'st_LS': 'Sesotho',
    'sn_ZW': 'Shona',
    'sd_PK': 'Sindhi',
    'si_LK': 'Sinhala',
    'sk_SK': 'Slovak',
    'sl_SI': 'Slovenian',
    'so_SO': 'Somali',
    'es_ES': 'Spanish',
    'es_MX': 'Spanish (Mexico)',
    'es_US': 'Spanish (United States)',
    'su_ID': 'Sundanese',
    'sw_TZ': 'Swahili',
    'sv_SE': 'Swedish',
    'tl_PH': 'Tagalog',
    'tg_TJ': 'Tajik',
    'ta_IN': 'Tamil',
    'tt_TT': 'Tatar',
    'te_IN': 'Telugu',
    'th_TH': 'Thai',
    'tr_TR': 'Turkish',
    'tk_TM': 'Turkmen',
    'uk_UA': 'Ukrainian',
    'ur_PK': 'Urdu',
    'ug_CN': 'Uyghur',
    'uz_UZ': 'Uzbek',
    'vi_VN': 'Vietnamese',
    'cy_GB': 'Welsh',
    'xh_ZA': 'Xhosa',
    'yi_IL': 'Yiddish',
    'yo_NG': 'Yoruba',
    'zu_ZA': 'Zulu',
}

# Maps alpha-1 code (e.g. 'en') -> full_code (e.g. 'en_US')
# When multiple variants exist, defaults to most common variant
ALPHA1_TO_FULL = {
    'af': 'af_ZA',
    'sq': 'sq_AL',
    'am': 'am_ET',
    'ar': 'ar_EG',
    'hy': 'hy_AM',
    'az': 'az_AZ',
    'eu': 'eu_ES',
    'be': 'be_BY',
    'bn': 'bn_BD',
    'bs': 'bs_BA',
    'bg': 'bg_BG',
    'ca': 'ca_ES',
    'ceb': 'ceb_PH',
    'ny': 'ny_MW',
    'zh': 'zh-Hans_CN',
    'co': 'co_FR',
    'hr': 'hr_HR',
    'cs': 'cs_CZ',
    'da': 'da_DK',
    'nl': 'nl_NL',
    'en': 'en_US',
    'eo': 'eo_WORLD',
    'et': 'et_EE',
    'fi': 'fi_FI',
    'fr': 'fr_FR',
    'fy': 'fy_NL',
    'gl': 'gl_ES',
    'ka': 'ka_GE',
    'de': 'de_DE',
    'el': 'el_GR',
    'gu': 'gu_IN',
    'ht': 'ht_HT',
    'ha': 'ha_NE',
    'haw': 'haw_US',
    'he': 'he_IL',
    'hi': 'hi_IN',
    'hmn': 'hmn_CN',
    'hu': 'hu_HU',
    'is': 'is_IS',
    'ig': 'ig_NG',
    'id': 'id_ID',
    'ga': 'ga_IE',
    'it': 'it_IT',
    'ja': 'ja_JP',
    'jv': 'jv_ID',
    'kn': 'kn_IN',
    'kk': 'kk_KZ',
    'km': 'km_KH',
    'rw': 'rw_RW',
    'ko': 'ko_KR',
    'ku': 'ku_IR',
    'ky': 'ky_KG',
    'lo': 'lo_LA',
    'la': 'la_VAT',
    'lv': 'lv_LV',
    'lt': 'lt_LT',
    'lb': 'lb_LU',
    'mk': 'mk_MK',
    'mg': 'mg_MG',
    'ms': 'ms_MY',
    'ml': 'ml_IN',
    'mt': 'mt_MT',
    'mi': 'mi_NZ',
    'mr': 'mr_IN',
    'mn': 'mn_MN',
    'my': 'my_MM',
    'ne': 'ne_NP',
    'no': 'no_NO',
    'or': 'or_OR',
    'ps': 'ps_AF',
    'fa': 'fa_IR',
    'pl': 'pl_PL',
    'pt': 'pt_PT',
    'pa': 'pa_PK',
    'ro': 'ro_RO',
    'ru': 'ru_RU',
    'sm': 'sm_WS',
    'gd': 'gd_GB',
    'sr': 'sr-Cyrl_RS',
    'st': 'st_LS',
    'sn': 'sn_ZW',
    'sd': 'sd_PK',
    'si': 'si_LK',
    'sk': 'sk_SK',
    'sl': 'sl_SI',
    'so': 'so_SO',
    'es': 'es_ES',
    'su': 'su_ID',
    'sw': 'sw_TZ',
    'sv': 'sv_SE',
    'tl': 'tl_PH',
    'tg': 'tg_TJ',
    'ta': 'ta_IN',
    'tt': 'tt_TT',
    'te': 'te_IN',
    'th': 'th_TH',
    'tr': 'tr_TR',
    'tk': 'tk_TM',
    'uk': 'uk_UA',
    'ur': 'ur_PK',
    'ug': 'ug_CN',
    'uz': 'uz_UZ',
    'vi': 'vi_VN',
    'cy': 'cy_GB',
    'xh': 'xh_ZA',
    'yi': 'yi_IL',
    'yo': 'yo_NG',
    'zu': 'zu_ZA',
}
